### ISSUE TITLE
Write user scenarios

### ISSUE THREAD

**Issue by vwochnik** [mirsmartgrp/docs#9]

**Comment by ghost** [comment]
Chapter 3 User Scenarios should only contain problem domain, use cases and requirements ( shortly )
The subchapter Risk Management should be deleted. The text for stakeholders in google drive must be rewritten.

**Comment by ghost** [comment]
please upload!

**Comment by Mazorius** [comment]
habe ich gestern bereits gemacht ... daher auch geschlossen ...

**Comment by Mazorius** [comment]
irgendwie hat der den push nicht gemacht ...... führe ich sofort aus!!!

**Comment by Mazorius** [comment]
Erledigt! Sorry Leute ... war echt keine Absicht dahinter.
